// ============================================================
// Federation v1 — two-relay integration tests
//
// Spawns two real relay processes configured as federation peers
// (A dials B; B allow-lists A) and verifies the spec's core
// behaviours end-to-end:
//
//   - mutual handshake establishes (visible via /health)
//   - a packet sent by a client on A reaches a client connected to B
//   - handshake rejection for unknown pubkeys
//   - loop prevention / no duplicate delivery
//
// Ed25519 keypairs are pre-generated by the test so both relays'
// allow-lists can be written before spawn.
// ============================================================

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as childProcess from 'node:child_process';
import * as path from 'node:path';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as nodeCrypto from 'node:crypto';
import { WebSocket } from 'ws';

const __dirname = path.dirname(new URL(import.meta.url).pathname);

// ---- key generation matching node/src/federation.ts storage shape ----

function generateFederationKeyFile(filePath: string): string {
  const { publicKey, privateKey } = nodeCrypto.generateKeyPairSync('ed25519');
  const spki = publicKey.export({ format: 'der', type: 'spki' }) as Buffer;
  const publicKeyHex = spki.subarray(spki.length - 32).toString('hex');
  const pkcs8 = privateKey.export({ format: 'der', type: 'pkcs8' }) as Buffer;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify({
    publicKeyHex,
    privateKeyPkcs8Base64: pkcs8.toString('base64'),
  }));
  return publicKeyHex;
}

// ---- relay harness ----

interface RelayHandle {
  proc: childProcess.ChildProcess;
  port: number;
  dir: string;
}

async function waitForHealth(port: number, proc: childProcess.ChildProcess, timeoutMs = 15000): Promise<void> {
  let exited = false;
  let exitCode: number | null = null;
  const errChunks: Buffer[] = [];
  proc.stderr?.on('data', (d: Buffer) => errChunks.push(d));
  proc.once('exit', (code) => { exited = true; exitCode = code; });
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (exited) {
      throw new Error(`relay exited early (${exitCode}): ${Buffer.concat(errChunks).toString().slice(-500)}`);
    }
    try {
      const res = await fetch(`http://127.0.0.1:${port}/health`);
      if (res.ok) return;
    } catch { /* not up yet */ }
    await new Promise((r) => setTimeout(r, 100));
  }
  throw new Error(`relay :${port} did not start (stderr: ${Buffer.concat(errChunks).toString().slice(-500)})`);
}

function spawnRelay(port: number, dir: string, env: Record<string, string>): RelayHandle {
  const nodeDir = path.resolve(__dirname, '../node');
  const distEntry = path.join(nodeDir, 'dist/index.js');
  const srcEntry = path.join(nodeDir, 'src/index.ts');
  const useCompiled = fs.existsSync(distEntry);
  const proc = childProcess.spawn(
    useCompiled ? 'node' : 'npx',
    useCompiled ? [distEntry] : ['tsx', srcEntry],
    {
      cwd: nodeDir,
      env: {
        ...process.env,
        PORT: String(port),
        DB_PATH: path.join(dir, 'relay.db'),
        NODE_ENV: 'test',
        ...env,
      },
      stdio: 'pipe',
    },
  );
  return { proc, port, dir };
}

function stopRelay(h: RelayHandle): void {
  h.proc.kill('SIGTERM');
  fs.rmSync(h.dir, { recursive: true, force: true });
}

async function getHealth(port: number): Promise<Record<string, number | string>> {
  const res = await fetch(`http://127.0.0.1:${port}/health`);
  return await res.json() as Record<string, number | string>;
}

async function waitForFederation(port: number, expectedPeers: number, timeoutMs = 15000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const h = await getHealth(port).catch(() => null);
    if (h && h.federationPeersConnected === expectedPeers) return;
    await new Promise((r) => setTimeout(r, 200));
  }
  throw new Error(`relay :${port} never reached federationPeersConnected=${expectedPeers}`);
}

// ---- packet construction (matches the relay's 31-byte header) ----

function buildPacket(destHashHex: string, payload: Uint8Array): Buffer {
  const header = Buffer.alloc(31);
  header.writeUInt8(1, 0);                          // version
  header.writeUInt8(0, 1);                          // flags
  Buffer.from(destHashHex, 'hex').copy(header, 2);  // destHash (8 bytes)
  nodeCrypto.randomBytes(16).copy(header, 10);      // senderEphId
  header.writeUInt8(3, 26);                         // ttl
  header.writeUInt32BE(payload.length, 27);         // payloadLen
  return Buffer.concat([header, Buffer.from(payload)]);
}

/** Connect a raw client WS, register destHashes, resolve when registered. */
function connectClient(port: number, destHashes: string[]): Promise<WebSocket> {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket(`ws://127.0.0.1:${port}`);
    ws.on('open', () => {
      ws.send(JSON.stringify({ type: 'hello', destHashes }));
      // Registration is processed synchronously server-side; a short
      // settle keeps the test deterministic without an ack protocol.
      setTimeout(() => resolve(ws), 200);
    });
    ws.on('error', reject);
  });
}

// ---- suite ----

describe('Federation v1 — two-relay integration', () => {
  const PORT_A = 19900;
  const PORT_B = 19901;
  let relayA: RelayHandle;
  let relayB: RelayHandle;
  let pubA: string;
  let pubB: string;

  beforeAll(async () => {
    const dirA = fs.mkdtempSync(path.join(os.tmpdir(), 'mw-fed-a-'));
    const dirB = fs.mkdtempSync(path.join(os.tmpdir(), 'mw-fed-b-'));

    pubA = generateFederationKeyFile(path.join(dirA, 'fed-key.json'));
    pubB = generateFederationKeyFile(path.join(dirB, 'fed-key.json'));

    // A dials B; B accepts inbound from A.
    fs.writeFileSync(path.join(dirA, 'fed-peers.json'), JSON.stringify({
      peers: [{ pubkey: pubB, url: `ws://127.0.0.1:${PORT_B}` }],
    }));
    fs.writeFileSync(path.join(dirB, 'fed-peers.json'), JSON.stringify({
      peers: [{ pubkey: pubA }],
    }));

    relayA = spawnRelay(PORT_A, dirA, {
      FEDERATION_KEY_FILE: path.join(dirA, 'fed-key.json'),
      FEDERATION_PEERS_FILE: path.join(dirA, 'fed-peers.json'),
    });
    relayB = spawnRelay(PORT_B, dirB, {
      FEDERATION_KEY_FILE: path.join(dirB, 'fed-key.json'),
      FEDERATION_PEERS_FILE: path.join(dirB, 'fed-peers.json'),
    });

    await Promise.all([
      waitForHealth(PORT_A, relayA.proc),
      waitForHealth(PORT_B, relayB.proc),
    ]);
  }, 30000);

  afterAll(() => {
    stopRelay(relayA);
    stopRelay(relayB);
  });

  it('peers establish a mutual handshake (visible via /health on both sides)', async () => {
    await waitForFederation(PORT_A, 1);
    await waitForFederation(PORT_B, 1);
    const hA = await getHealth(PORT_A);
    const hB = await getHealth(PORT_B);
    expect(hA.federationPeersConfigured).toBe(1);
    expect(hB.federationPeersConfigured).toBe(1);
  });

  it('a packet sent on relay A reaches a client connected to relay B', async () => {
    const destHash = nodeCrypto.randomBytes(8).toString('hex');

    // Bob connects to B and registers the hash.
    const bob = await connectClient(PORT_B, [destHash]);
    const received: Buffer[] = [];
    const gotPacket = new Promise<void>((resolve) => {
      bob.on('message', (raw: Buffer, isBinary: boolean) => {
        if (isBinary) { received.push(raw); resolve(); }
      });
    });

    // Alice connects to A (no registration needed for sending) and sends.
    const alice = await connectClient(PORT_A, []);
    const packet = buildPacket(destHash, new Uint8Array([1, 2, 3, 4]));
    alice.send(packet, { binary: true });

    await Promise.race([
      gotPacket,
      new Promise<void>((_, reject) =>
        setTimeout(() => reject(new Error('packet never crossed the federation link')), 8000)),
    ]);

    expect(received.length).toBe(1);
    // Payload integrity end-to-end.
    expect(Buffer.compare(received[0], packet)).toBe(0);

    alice.close();
    bob.close();
  });

  it('the same packet is not delivered twice (loop prevention)', async () => {
    const destHash = nodeCrypto.randomBytes(8).toString('hex');
    const bob = await connectClient(PORT_B, [destHash]);
    let deliveries = 0;
    bob.on('message', (_raw: Buffer, isBinary: boolean) => { if (isBinary) deliveries++; });

    const alice = await connectClient(PORT_A, []);
    alice.send(buildPacket(destHash, new Uint8Array([9])), { binary: true });

    // Give the network time to do anything pathological.
    await new Promise((r) => setTimeout(r, 3000));
    expect(deliveries).toBe(1);

    alice.close();
    bob.close();
  });

  it('rejects a federation handshake from an unknown pubkey', async () => {
    // Mint a keypair that is NOT in B's allow-list and attempt the handshake.
    const { publicKey, privateKey } = nodeCrypto.generateKeyPairSync('ed25519');
    const spki = publicKey.export({ format: 'der', type: 'spki' }) as Buffer;
    const evilPubHex = spki.subarray(spki.length - 32).toString('hex');
    void privateKey;

    const ws = new WebSocket(`ws://127.0.0.1:${PORT_B}`, 'meshwhisper-federation.v1');
    const outcome = await new Promise<'rejected' | 'accepted'>((resolve) => {
      ws.on('open', () => {
        // ClientHello with the unknown pubkey
        const hello = Buffer.alloc(53);
        hello.writeUInt8(0x01, 0);
        Buffer.from(evilPubHex, 'hex').copy(hello, 1);
        nodeCrypto.randomBytes(16).copy(hello, 33);
        hello.writeUInt32BE(0, 49);
        ws.send(hello, { binary: true });
      });
      ws.on('message', (raw: Buffer) => {
        // ServerHello with version 0x00 = rejection
        if (raw.length === 53 && raw.readUInt8(0) === 0x00) resolve('rejected');
        else resolve('accepted');
      });
      ws.on('close', () => resolve('rejected'));
      setTimeout(() => resolve('rejected'), 5000);
    });
    expect(outcome).toBe('rejected');
    try { ws.close(); } catch { /* already closed */ }
  });

  it('federation metrics are exposed on /metrics', async () => {
    const res = await fetch(`http://127.0.0.1:${PORT_A}/metrics`);
    const body = await res.text();
    expect(body).toContain('meshwhisper_federation_peers_connected 1');
    expect(body).toMatch(/meshwhisper_federation_forwards_sent_total \d+/);
  });
});
